# Imports

In [28]:
import os
import json
import itables
import pandas as pd
from helpers import *

# itables.init_notebook_mode(all_interactive=True)

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

# Wave Data Extraction
Parse raw data sets to extract questions relevant to the research topic. Relevant questions ask respondants about either military aid for Ukraine or economic sanctions on Russia.
Additionally extract fieldwork timelines during which respondants were surveyed.

In [6]:
collected = []

for file in os.listdir(EB_BASE_PATH):
    collected.append(parse_doc(file))

collected.sort(key=lambda k: k["wave_id"])
df = pd.DataFrame(collected)
df

,eb_n,wave_id,fw_start,fw_end,season,questions,q_ids
0,eb97,97.5,2022-06-17,2022-07-17,Summer 2022,"[QE2.1. The EU has taken a series of actions as a response to Russia’s invasion in Ukraine. To what extent you agree or disagree with each of these actions taken. :-Imposing economic sanctions on Russian government, companies and individuals, QE2.3. The EU has taken a series of actions as a response to Russia’s invasion in Ukraine. To what extent you agree or disagree with each of these actions taken. :-Financing supply and delivery of military equipment to Ukraine]","[QE2_1, QE2_3]"
1,eb98,98.2,2023-01-12,2023-02-06,Spring 2023,"[QE2.1. The EU has taken a series of actions as a response to Russia's invasion of Ukraine. To what extent you agree or disagree with each of these actions taken. :-Imposing economic sanctions on Russian government, companies and individuals, QE2.3. The EU has taken a series of actions as a response to Russia's invasion of Ukraine. To what extent you agree or disagree with each of these actions taken. :-Financing the purchase and supply of military equipment to Ukraine]","[QE2_1, QE2_3]"
2,eb99,99.4,2023-05-31,2023-06-25,Spring 2023,"[QE2.1. The EU has taken a series of actions as a response to Russia's invasion of Ukraine. To what extent you agree or disagree with each of these actions taken. :-Imposing economic sanctions on Russian government, companies and individuals, QE2.3. The EU has taken a series of actions as a response to Russia's invasion of Ukraine. To what extent you agree or disagree with each of these actions taken. :-Financing the purchase and supply of military equipment to Ukraine]","[QE2_1, QE2_3]"
3,eb100,100.2,2023-10-23,2023-11-17,Fall 2023,"[QD2.1. The EU has taken a series of actions as a response to Russia's invasion of Ukraine. To what extent you agree or disagree with each of these actions taken. :-Imposing economic sanctions on Russian government, companies and individuals, QD2.3. The EU has taken a series of actions as a response to Russia's invasion of Ukraine. To what extent you agree or disagree with each of these actions taken. :-Financing the purchase and supply of military equipment to Ukraine]","[QD2_1, QD2_3]"
4,eb101,101.3,2024-04-02,2024-05-09,Spring 2024,"[QD2.1. The EU has taken a series of actions as a response to Russia's invasion of Ukraine. To what extent you agree or disagree with each of these actions taken. :-Imposing economic sanctions on Russian government, companies and individuals, QD2.2. The EU has taken a series of actions as a response to Russia's invasion of Ukraine. To what extent you agree or disagree with each of these actions taken. :-Financing the purchase and supply of military equipment to Ukraine]","[QD2_1, QD2_2]"
5,eb102,102.2,2024-10-10,2024-11-05,Fall 2024,"[QD2.1. The EU has taken a series of actions as a response to Russia’s invasion of Ukraine. To what extent you agree or disagree with each of these actions taken?:-Imposing economic sanctions on Russian government, companies and individuals, QD2.2. The EU has taken a series of actions as a response to Russia’s invasion of Ukraine. To what extent you agree or disagree with each of these actions taken?:-Financing the purchase and supply of military equipment to Ukraine]","[QD2_1, QD2_2]"
6,eb103,103.3,2025-03-26,2025-04-22,Spring 2025,"[QD2.1. The EU has taken a series of actions as a response to Russia’s invasion of Ukraine. To what extent you agree or disagree with each of these actions taken.:-Imposing economic sanctions on Russian government, companies and individuals, QD2.2. The EU has taken a series of actions as a response to Russia’s invasion of Ukraine. To what extent you agree or disagree with each of these actions taken.:-Financing the purchase and supply of military equipment to Ukraine]","[QD2_1, QD2_2]"
7,eb104,104.1,2025-10-09,2025-11-05,Fall 2025,"[QD2.1. The EU has taken a series of actions as a response to Russia’s invasion of Ukraine. To what extent you agree or disagree with each of these actions taken.:-Imposing economic sanctions on Russian government, companies and individuals, QD2.2. The EU has taken a series of actions as a response to Russia’s invasion of Ukraine. To what extent you agree or disagree with each of these actions taken.:-Financing the purchase and supply of military equipment to Ukraine]","[QD2_1, QD2_2]"
8,eb105,105.2,2026-03-12,2026-04-05,Spring 2026,"[QD2.1. The EU has taken a series of actions as a response to Russia’s invasion of Ukraine. To what extent you agree or disagree with each of these actions taken?:-Imposing economic sanctions on Russian government, companies and individuals (including use of immobilised Russian assets to finance support for Ukraine), QD2.2. The EU has taken a series of actions as a response to Russia’s invasion of Ukraine. To what extent you agree or disagree with each of these actions taken?:-Financing the purchase and supply of military equipment to Ukraine]","[QD2_1, QD2_2]"

In [17]:
if os.path.exists("data/interim/wave_questions.csv"):
    questions = pd.read_csv("data/interim/wave_questions.csv")
else:
    qs = pd.DataFrame(df["questions"].tolist(), index=df.index)
    qs.columns = ["q1", "q2"]
    qs["q1"] = qs["q1"].apply(lambda v: f"{v.split(" ", 1)[0]} {v.split(":-")[-1]}")
    qs["q2"] = qs["q2"].apply(lambda v: f"{v.split(" ", 1)[0]} {v.split(":-")[-1]}")
    questions = df.join(qs).drop(columns=["questions", "q_ids"])

    with open("data/interim/wave_questions.csv", "w") as f:
        questions.to_csv(f, index=False)

questions

,eb_n,wave_id,fw_start,fw_end,season,q1,q2
0,eb97,97.5,2022-06-17,2022-07-17,Summer 2022,"QE2.1. Imposing economic sanctions on Russian government, companies and individuals",QE2.3. Financing supply and delivery of military equipment to Ukraine
1,eb98,98.2,2023-01-12,2023-02-06,Spring 2023,"QE2.1. Imposing economic sanctions on Russian government, companies and individuals",QE2.3. Financing the purchase and supply of military equipment to Ukraine
2,eb99,99.4,2023-05-31,2023-06-25,Spring 2023,"QE2.1. Imposing economic sanctions on Russian government, companies and individuals",QE2.3. Financing the purchase and supply of military equipment to Ukraine
3,eb100,100.2,2023-10-23,2023-11-17,Fall 2023,"QD2.1. Imposing economic sanctions on Russian government, companies and individuals",QD2.3. Financing the purchase and supply of military equipment to Ukraine
4,eb101,101.3,2024-04-02,2024-05-09,Spring 2024,"QD2.1. Imposing economic sanctions on Russian government, companies and individuals",QD2.2. Financing the purchase and supply of military equipment to Ukraine
5,eb102,102.2,2024-10-10,2024-11-05,Fall 2024,"QD2.1. Imposing economic sanctions on Russian government, companies and individuals",QD2.2. Financing the purchase and supply of military equipment to Ukraine
6,eb103,103.3,2025-03-26,2025-04-22,Spring 2025,"QD2.1. Imposing economic sanctions on Russian government, companies and individuals",QD2.2. Financing the purchase and supply of military equipment to Ukraine
7,eb104,104.1,2025-10-09,2025-11-05,Fall 2025,"QD2.1. Imposing economic sanctions on Russian government, companies and individuals",QD2.2. Financing the purchase and supply of military equipment to Ukraine
8,eb105,105.2,2026-03-12,2026-04-05,Spring 2026,"QD2.1. Imposing economic sanctions on Russian government, companies and individuals (including use of immobilised Russian assets to finance support for Ukraine)",QD2.2. Financing the purchase and supply of military equipment to Ukraine

Looking at the extracted questions from each wave, a change in the wording of the questions only happens twice: *QE2.3* in wave *97.5* and *QD2.1* in wave *105.2*. However, given that the deviations in wording are relatively minor - *97.5-QE2.3* implies the same thing as *98.2-QE2.3* and *105.2-QD2.1* clarifies the scope of the sanctions - a consistent analysis over time can still be made.

## Per-country score extraction
This takes a while to run, but saves to data/interim/wave_scores.json.

In [49]:
if os.path.exists("data/interim/wave_scores.json"):
    with open("data/interim/wave_scores.json", "r") as f:
        data = json.load(f)
else:
    data = {}

    for row in df[["eb_n", "q_ids"]].itertuples():
        data[row.eb_n] = collect_scores(row.eb_n, row.q_ids)  # type: ignore[arg-type]

    with open("data/interim/wave_scores.json", "w") as f:
        json.dump(data, f, indent=4)

series = pd.Series({
    (wave, q, COUNTRY_CODES[country]): metrics
    for wave, questions in data.items()
    for q, countries in questions.items()
    for country, metrics in countries.items()
})

wdf = pd.DataFrame(series.tolist(), index=series.index)
wdf.index.names = ['wave', 'question', 'country']

pd.set_option("display.max_rows", None)
wdf

                            total  total_agree  total_disagree  totally_agree  \
wave  question country
eb97  QE2_1    Belgium       1009          819             178            437
               Bulgaria      1038          477             440            205
               Czechia       1015          727             249            484
               Denmark       1037          956              67            762
               Germany       1507         1229             224            859
               Estonia       1026          758             194            562
               Ireland       1017          918              64            557
               Greece        1010          603             356            278
               Spain         1009          789             131            484
               France        1010          700             202            362
               Croatia       1000          776             182            399
               Italy         1023          781             195            407
               Cyprus         503          243             222            105
               Latvia        1028          710             251            524
               Lithuania     1001          796             189            482
               Luxembourg     506          355             102            154
               Hungary       1026          669             331            310
               Malta          503          408              78            249
               Netherlands   1013          889             114            589
               Austria       1006          642             322            332
               Poland        1016          941              61            579
               Portugal      1009          950              26            554
               Romania       1042          716             248            331
               Slovenia      1001          624             341            347
               Slovakia      1033          606             401            358
               Finland       1045          921              82            672
               Sweden        1035          967              63            739
      QE2_3    Belgium       1009          732             259            320
               Bulgaria      1038          363             598            145
               Czechia       1015          571             419            323
               Denmark       1037          943              82            622
               Germany       1507         1065             369            606
               Estonia       1026          767             191            553
               Ireland       1017          878              89            468
               Greece        1010          413             560            167
               Spain         1009          671             236            369
               France        1010          623             273            267
               Croatia       1000          740             225            359
               Italy         1023          582             378            237
               Cyprus         503          222             248             87
               Latvia        1028          739             224            512
               Lithuania     1001          827             161            491
               Luxembourg     506          315             152            126
               Hungary       1026          590             411            240
               Malta          503          369             117            229
               Netherlands   1013          855             143            527
               Austria       1006          506             460            227
               Poland        1016          927              73            524
               Portugal      1009          876              90            387
               Romania       1042          632             332            270
               Slovenia      1001          539             428            276
               Slovakia      1033          512             499            276
               Finland       1045          929              67            624
               Sweden        1035          947              81            606
eb98  QE2_1    Belgium       1035          793             208            374
               Bulgaria      1033          491             423            198
               Czechia       1025          713             267            449
               Denmark       1015          916              71            701
               Germany       1532         1135             330            700
               Estonia        982          700             195            460
               Ireland       1008          865              98            524
               Greece        1014          564             379            226
               Spain         1011          742             207            458
               France        1015          664             240            331
               Croatia       1000          819             158            439
               Italy         1026          763             217            359
               Cyprus         505          265             216            120
               Latvia        1039          770             165            541
               Lithuania     1003          846             126            572
               Luxembourg     510          383             105            163
               Hungary       1040          586             406            234
               Malta          504          395              85            258
               Netherlands   1031          914             108            699
               Austria       1012          702             263            333
               Poland        1014          909              91            543
               Portugal      1008          898              44            521
               Romania       1041          690             264            328
               Slovenia      1001          611             324            318
               Slovakia      1004          492             440            260
               Finland       1017          861              92            655
               Sweden        1043          984              46            787
      QE2_3    Belgium       1035          707             294            246
               Bulgaria      1033          343             585            122
               Czechia       1025          513             483            248
               Denmark       1015          908              81            609
               Germany       1532          968             479            474
               Estonia        982          708             176            440
               Ireland       1008          823             123            436
               Greece        1014          373             594            138
               Spain         1011          657             292            327
               France        1015          612             296            259
               Croatia       1000          730             240            318
               Italy         1026          577             402            243
               Cyprus         505          248             236            123
               Latvia        1039          801             148            509
               Lithuania     1003          886              89            551
               Luxembourg     510          327             158            122
               Hungary       1040          523             472            191
               Malta          504          381             107            247
               Netherlands   1031          924              94            637
               Austria       1012          505             463            208
               Poland        1014          900              99            482
               Portugal      1008          824             100            390
               Romania       1041          576             376            232
               Slovenia      1001          528             409            283
               Slovakia      1004          374             569            169
               Finland       1017          894              74            626
               Sweden        1043          958              65            708
eb99  QE2_1    Belgium       1014          777             207            349
               Bulgaria      1028          474             409            206
               Czechia       1035          764             219            468
               Denmark       1016          902              84            647
               Germany       1553         1144             349            667
               Estonia       1002          627             254            374
               Ireland       1008          898              71            553
               Greece        1013          588             359            244
               Spain         1015          726             197            374
               France        1014          647             258            330
               Croatia       1003          805             179            417
               Italy         1033          725             251            288
               Cyprus         504          178             283             82
               Latvia        1025          724             209            470
               Lithuania     1008          847             118            529
               Luxembourg     507          378             107            135
               Hungary       1021          602             382            205
               Malta          512          391              74            173
               Netherlands   1002          861             122            632
               Austria       1006          553             397            260
               Poland        1007          897              93            482
               Portugal      1004          945              18            447
               Romania       1056          684             315            281
               Slovenia      1010          592             365            301
               Slovakia      1001          506             409            197
               Finland       1003          870              86            627
               Sweden        1025          965              46            786
      QE2_3    Belgium       1014          694             285            199
               Bulgaria      1028          312             593            145
               Czechia       1035          551             438            266
               Denmark       1016          902              86            601
               Germany       1553          962             535            455
               Estonia       1002          638             282            329
               Ireland       1008          795             147            463
               Greece        1013          436             534            170
               Spain         1015          608             320            266
               France        1014          585             335            203
               Croatia       1003          723             257            299
               Italy         1033          615             365            201
               Cyprus         504          177             296             64
               Latvia        1025          764             175            463
               Lithuania     1008          850             131            500
               Luxembourg     507          355             132            114
               Hungary       1021          453             543            155
               Malta          512          329             169            127
               Netherlands   1002          854             130            533
               Austria       1006          403             564            157
               Poland        1007          862             121            413
               Portugal      1004          905              54            355
               Romania       1056          585             421            187
               Slovenia      1010          501             461            217
               Slovakia      1001          375             564            112
               Finland       1003          895              72            593
               Sweden        1025          948              60            734
eb100 QD2_1    Belgium       1016          789             199            351
               Bulgaria      1011          451             402            173
               Czechia       1011          675             272            399
               Denmark       1012          886              92            664
               Germany       1527         1096             342            614
               Estonia       1003          667             238            414
               Ireland       1016          865              95            519
               Greece        1012          562             381            220
               Spain         1006          695             222            370
               France        1025          686             225            315
               Croatia       1032          828             168            367
               Italy         1024          716             251            280
               Cyprus         506          159             296             55
               Latvia        1010          677             221            419
               Lithuania     1013          807             149            525
               Luxembourg     504          365             120            180
               Hungary       1022          565             421            188
               Malta          504          347             101            181
               Netherlands   1011          894             101            600
               Austria       1005          633             325            297
               Poland        1025          915              92            470
               Portugal      1031          964              29            427
               Romania       1062          667             313            311
               Slovenia      1017          583             397            297
               Slovakia      1006          508             410            199
               Finland       1009          897              57            676
               Sweden        1051         1003              34            778
      QD2_3    Belgium       1016          611             373            177
               Bulgaria      1011          308             601            107
               Czechia       1011          425             541            207
               Denmark       1012          840             136            549
               Germany       1527          922             513            423
               Estonia       1003          619             297            328
               Ireland       1016          737             221            325
               Greece        1012          376             597            145
               Spain         1006          534             371            211
               France        1025          562             362            197
               Croatia       1032          758             238            278
               Italy         1024          515             452            181
               Cyprus         506          158             309             55
               Latvia        1010          708             216            363
               Lithuania     1013          840             132            479
               Luxembourg     504          300             169             98
               Hungary       1022          443             546            143
               Malta          504          304             184            119
               Netherlands   1011          854             144            449
               Austria       1005          436             529            176
               Poland        1025          870             127            339
               Portugal      1031          850             125            208
               Romania       1062          523             479            211
               Slovenia      1017          471             516            189
               Slovakia      1006          338             612            112
               Finland       1009          904              56            632
               Sweden        1051          959              66            747
eb101 QD2_1    Belgium       1006          750             228            371
               Bulgaria      1046          478             462            167
               Czechia       1026          674             317            406
               Denmark       1001          903              82            651
               Germany       1559         1123             363            625
               Estonia       1001          662             270            375
               Ireland       1003          843              79            486
               Greece        1011          570             364            206
               Spain         1002          730             207            356
               France        1004          623             282            296
               Croatia       1003          760             222            326
               Italy         1070          738             303            286
               Cyprus         507          203             274             85
               Latvia        1009          650             232            459
               Lithuania     1005          796             157            492
               Luxembourg     506          360             118            168
               Hungary       1019          579             407            186
               Malta          500          345             141            150
               Netherlands   1067          918             141            632
               Austria       1011          672             296            312
               Poland        1006          891              92            428
               Portugal      1000          914              38            511
               Romania       1038          722             264            259
               Slovenia      1004          544             423            200
               Slovakia      1006          593             335            215
               Finland       1000          879              94            618
               Sweden        1013          959              51            730
      QD2_2    Belgium       1006          640             350            166
               Bulgaria      1046          334             647             85
               Czechia       1026          502             494            232
               Denmark       1001          904              86            565
               Germany       1559          958             547            344
               Estonia       1001          629             316            289
               Ireland       1003          686             222            316
               Greece        1011          389             571             95
               Spain         1002          553             380            204
               France        1004          527             389            191
               Croatia       1003          698             286            203
               Italy         1070          517             535            154